### ISSUE TITLE
A question about quant_cache

### ISSUE THREAD

**Issue by chbw818** [ruisizhang123/EmMark#1]
Hi!Great Work!
However,when i try to run the code, i met a question.
I have successfully operated the `save` step in the readme,when I try to run `watermark` step,an error occurred.
```
Traceback (most recent call last):
  File "/root/autodl-tmp/EmMark/int4_wm/awq/watermark.py", line 141, in <module>
    main()
  File "/root/autodl-tmp/EmMark/int4_wm/awq/watermark.py", line 109, in main
    model, enc = load_model_and_enc(args, q_config, max_memory)
  File "/root/autodl-tmp/EmMark/int4_wm/awq/watermark.py", line 84, in load_model_and_enc
    load_checkpoint_in_model(model, checkpoint=args.load_quant, device_map=device_map, offload_state_dict=True,)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1645, in load_checkpoint_in_model
    raise ValueError(
ValueError: `checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded checkpoint, or a folder containing a sharded checkpoint or the whole state dict, but got /root/autodl-tmp/EmMark/llm/quant_cache/opt-2.7b-w4-g128.pt.
```
I wonder how to solve this and I could not find the `opt-2.7b-w4-g128.pt`

**Comment by ruisizhang123** [comment]
Hi,

I was using the quantized checkpoint from AWQ, you could download them following this link: https://github.com/mit-han-lab/llm-awq/tree/5908bb149c9260562a89cc171f098ab202181652?tab=readme-ov-file#awq-model-zoo

**Comment by chbw818** [comment]
Thank you for your quick reply!
